# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'success.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_success(object):
    def setupUi(self, success):
        success.setObjectName("success")
        success.resize(400, 300)
        self.ok = QtWidgets.QPushButton(success)
        self.ok.setGeometry(QtCore.QRect(130, 200, 121, 41))
        self.ok.setObjectName("ok")

        self.ok.clicked.connect(self.close)

        self.label = QtWidgets.QLabel(success)
        self.label.setGeometry(QtCore.QRect(80, 70, 241, 91))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(success)
        QtCore.QMetaObject.connectSlotsByName(success)

    def retranslateUi(self, success):
        _translate = QtCore.QCoreApplication.translate
        success.setWindowTitle(_translate("success", "success"))
        self.ok.setText(_translate("success", "OK"))
        self.label.setText(_translate("success", "Successful!"))

    def close(self):
        import sys
        app = QtWidgets.QApplication(sys.argv)
        sys.exit(app.exec_())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    success = QtWidgets.QDialog()
    ui = Ui_success()
    ui.setupUi(success)
    success.show()
    sys.exit(app.exec_())
