# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

class Ui_view(object):
    def setupUi(self, view):
        view.setObjectName("view")
        view.resize(1129, 665)
        self.centralwidget = QtWidgets.QWidget(view)
        self.centralwidget.setObjectName("centralwidget")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(900, 270, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(18)
        self.close.setFont(font)
        self.close.setObjectName("close")

        self.close.clicked.connect(view.close)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 1041, 91))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 350, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 310, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 270, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 230, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 470, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 430, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 390, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(50, 510, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 150, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(210, 110, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(170, 150, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(200, 190, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(220, 230, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(270, 270, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(160, 310, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(120, 350, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(220, 390, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(260, 430, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(240, 470, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(130, 510, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.pid = QtWidgets.QLineEdit(self.centralwidget)
        self.pid.setGeometry(QtCore.QRect(890, 210, 151, 31))
        self.pid.setObjectName("pid")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(740, 200, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.View = QtWidgets.QPushButton(self.centralwidget)
        self.View.setGeometry(QtCore.QRect(740, 270, 151, 71))

        self.View.clicked.connect(self.which)

        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(18)
        self.View.setFont(font)
        self.View.setObjectName("View")
        view.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(view)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 27))
        self.menubar.setObjectName("menubar")
        view.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(view)
        self.statusbar.setObjectName("statusbar")
        view.setStatusBar(self.statusbar)

        self.retranslateUi(view)
        QtCore.QMetaObject.connectSlotsByName(view)

    def retranslateUi(self, view):
        _translate = QtCore.QCoreApplication.translate
        view.setWindowTitle(_translate("view", "view"))
        self.close.setText(_translate("view", "Close"))
        self.label.setText(_translate("view", "HOSPITAL MANAGEMENT"))
        self.label_2.setText(_translate("view", "Patient Name:"))
        self.label_3.setText(_translate("view", "Blood Group:"))
        self.label_4.setText(_translate("view", "Fees:"))
        self.label_5.setText(_translate("view", "Allergies:"))
        self.label_6.setText(_translate("view", "Haemoglobin Leves:"))
        self.label_7.setText(_translate("view", "Disease Caused:"))
        self.label_8.setText(_translate("view", "Patient\'s Address:"))
        self.label_9.setText(_translate("view", "Gardian Phone No:"))
        self.label_10.setText(_translate("view", "Gardian Name:"))
        self.label_11.setText(_translate("view", "Notes:"))
        self.label_12.setText(_translate("view", "Patient ID:"))
        self.label_13.setText(_translate("view", "Pname"))
        self.label_14.setText(_translate("view", "Pid"))
        self.label_15.setText(_translate("view", "Blood"))
        self.label_16.setText(_translate("view", "Disease"))
        self.label_17.setText(_translate("view", "Haemoglobin"))
        self.label_18.setText(_translate("view", "Allergies"))
        self.label_19.setText(_translate("view", "Fees"))
        self.label_20.setText(_translate("view", "Gardname"))
        self.label_21.setText(_translate("view", "Gardphone"))
        self.label_22.setText(_translate("view", "Add"))
        self.label_23.setText(_translate("view", "Notes"))
        self.label_24.setText(_translate("view", "Enter Patient ID:"))
        self.View.setText(_translate("view", "View"))

    def which(self):
        try:

            pid = self.pid.text()
            
            mydb = mc.connect(
                host = 'localhost',
                user='root',
                password='password',
                database='ohms'

            )

            mycursor = mydb.cursor()
            query = "select * from overflow where pid = " + pid +";"
            mycursor.execute(query)
            data = mycursor.fetchall()
            mydb.close()
            print(data)
            print("Successful")

            listq=[]
            for i in data:
                for j in i:
                    print(j)
                    listq.append(j)
            for k in listq:
                a = k
                listq.pop(0)
                print(a)
                break
            for k in listq:
                b = k
                listq.pop(0)
                print(b)
                break
            for k in listq:
                c = k
                listq.pop(0)
                print(c)
                break
            for k in listq:
                d = k
                listq.pop(0)
                print(d)
                break
            for k in listq:
                e= str(k)
                listq.pop(0)
                print(e)
                break
            for k in listq:
                f= k
                listq.pop(0)
                print(f)
                break
            for k in listq:
                g = str(k)
                listq.pop(0)
                print(g)
                break
            for k in listq:
                h= k
                listq.pop(0)
                print(h)
                break
            for k in listq:
                z = str(k)
                listq.pop(0)
                print(z)
                break
            for k in listq:
                u = k
                listq.pop(0)
                print(u)
                break
            for k in listq:
                uj = k
                listq.pop(0)
                print(uj)
                break
            self.label_13.setText(a)
            self.label_14.setText(b)
            self.label_15.setText(c)
            self.label_16.setText(d)
            self.label_17.setText(e)
            self.label_18.setText(f)
            self.label_19.setText(g)
            self.label_20.setText(h)
            self.label_21.setText(z)
            self.label_22.setText(u)
            self.label_23.setText(uj)


        except mc.Error as e:
            print("smth is wrong i can feel it")
            print(query)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    view = QtWidgets.QMainWindow()
    ui = Ui_view()
    ui.setupUi(view)
    view.show()
    sys.exit(app.exec_())
